Adding guards to service startup

diff --git a/scripts/airpi b/scripts/airpi
--- a/scripts/airpi
+++ b/scripts/airpi
@@ -26,18 +26,30 @@ DATA=${DATA:-'/opt/airpi/'}
 [ -d $DATA ] || mkdir -p $DATA
 
 # Process' binaries
-AIRMON=`which airmon-ng`
-AIRDMP=`which airodump-ng`
+AIRMON=${AIRMONBIN:-which airmon-ng}
+AIRDMP=${AIRDMPBIN:-which airodump-ng}
 
 
 start() {
   log_daemon_msg "Starting airpi daemon" "airpi"
+
+  if [ -z $AIRMON ] || [ -z $AIRDMP ]; then
+    log_failure_msg "airpi: missing aircrack-ng installation"
+    exit 1
+  fi
+
   $AIRMON | grep -iP "^mon[0-9]+"
-  [ $? == "0" ] && log_failure_msg "airpi: requires exclusive control of monitor mode" && exit 1
+  if [ $? == "0" ]; then
+    log_failure_msg "airpi: requires exclusive control of monitor mode"
+    exit 2
+  fi
 
   $AIRMON start $DEVICE 
-  $AIRMON | grep -iP "^mon0"
-  [ $? != "0" ] && log_failure_msg "airpi: failed to start monitor mode on $DEVICE" && exit 2
+  $AIRMON | grep -iP "^mon0" | grep -iP $DEVICE
+  if [ $? != "0" ]; then
+    log_failure_msg "airpi: failed to start monitor mode on $DEVICE"
+    exit 3
+  fi
 
   start-stop-daemon --pidfile $PIDFILE -m \
   -b -d $DATA \
